name: HfFileSystem Test

on: [push]

jobs:
  depstest:
    name: HfFileSystem Test
    runs-on: ${{ matrix.os }}
    strategy:
    matrix:
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
        python-version:
          - '3.8'
          - '3.10'
          - '3.10.6'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 20
        submodules: 'recursive'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade tools
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Test
      run: python fs_test.py
    - name: Run Post Test In New Thread
      run: python post_test.py
